import test from 'node:test';
import assert from 'node:assert/strict';
import { mountHelperManagement } from '../ui/helper-management.ts';
class Element extends EventTarget {
 children:Element[]=[];parentElement:Element|null=null;dataset:Record<string,string>={};attrs=new Map<string,string>();className='';hidden=false;disabled=false;type='';text='';value='';
 readonly tag:string; readonly ownerDocument:Doc;
 constructor(tag:string,ownerDocument:Doc){super();this.tag=tag;this.ownerDocument=ownerDocument}
 get textContent():string{return this.text+this.children.map(n=>n.textContent).join('')}set textContent(t:string){this.replaceChildren();this.text=t}
 get isConnected():boolean{return this===this.ownerDocument.body||!!this.parentElement?.isConnected}
 contains(n:Element|null):boolean{return !!n&&(this===n||this.children.some(c=>c.contains(n)))}
 append(...nodes:Element[]){for(const node of nodes){node.remove();node.parentElement=this;this.children.push(node)}}
 insertBefore(node:Element,before:Element|null){node.remove();node.parentElement=this;const i=before?this.children.indexOf(before):-1;if(i<0)this.children.push(node);else this.children.splice(i,0,node)}
 replaceChildren(...nodes:Element[]){for(const node of [...this.children])node.remove();this.text='';this.append(...nodes)}
 remove(){if(!this.parentElement)return;if(this.contains(this.ownerDocument.activeElement))this.ownerDocument.activeElement=this.ownerDocument.body;this.parentElement.children=this.parentElement.children.filter(n=>n!==this);this.parentElement=null}
 setAttribute(k:string,v:string){this.attrs.set(k,v)}getAttribute(k:string){return this.attrs.get(k)??null}
 querySelectorAll(t:string):Element[]{return this.children.flatMap(n=>[...(n.tag===t?[n]:[]),...n.querySelectorAll(t)])}
 querySelector(t:string){return this.querySelectorAll(t)[0]??null}
 focus(){if(this.isConnected&&!this.disabled)this.ownerDocument.activeElement=this}
 click(){if(!this.disabled)this.dispatchEvent(new Event('click'))}
}
class Doc {body=new Element('body',this);activeElement=this.body;location=new URL('http://localhost:43120/');defaultView:any={};constructor(){this.defaultView.top=this.defaultView}createElement(t:string){return new Element(t,this)}}
function fixture(t:import('node:test').TestContext,url='http://localhost:43120/',framed=false){const doc=new Doc();doc.location=new URL(url);if(framed)doc.defaultView.top={};const old=new Map(['document','HTMLElement'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));Object.defineProperty(globalThis,'document',{configurable:true,value:doc});Object.defineProperty(globalThis,'HTMLElement',{configurable:true,value:Element});const mount=mountHelperManagement(doc.body as unknown as HTMLElement);t.after(()=>{mount.destroy();for(const[k,v]of old){if(v)Object.defineProperty(globalThis,k,v);else Reflect.deleteProperty(globalThis,k)}});return{doc,mount,button(label:string){const b=doc.body.querySelectorAll('button').find(b=>b.textContent===label);assert.ok(b,label);return b},output:()=>doc.body.querySelector('output')!}}
const tick=()=>new Promise<void>(r=>setImmediate(r));
function deferred(){let resolve!:(r:Response)=>void;const promise=new Promise<Response>(r=>resolve=r);return{promise,resolve}}
const entry={id:'11111111-1111-4111-8111-111111111111',origin:'chrome-extension://fixture',createdAt:'2026-09-17T00:00:00Z',revoked:false};
test('extension, remote and framed pages get no management controls or network requests',t=>{const fetch=t.mock.method(globalThis,'fetch',async()=>{throw Error('unexpected')});for(const[url,frame]of [['chrome-extension://fixture/index.html',false],['http://remote.test/',false],['http://localhost/',true]]as const){const f=fixture(t,url,frame);f.mount.open();assert.equal(f.doc.body.children.length,0);f.mount.destroy()}assert.equal(fetch.mock.callCount(),0)});
test('Show/Renew is explicit, preserves zeroes, and clears an older code before an uncertain replacement',async t=>{const requests:RequestInit[]=[];let fail=false;t.mock.method(globalThis,'fetch',async(url:string,init:RequestInit)=>{requests.push(init);if(fail)throw Error('secret');return Response.json(url.endsWith('browsers')?{browsers:[entry]}:{code:'001234',expiresInSeconds:300,singleUse:true})});const f=fixture(t);assert.equal(requests.length,0);f.mount.open();await tick();f.button('Show pairing code').click();await tick();assert.equal(f.output().textContent,'001234');fail=true;f.button('Renew pairing code').click();assert.equal(f.output().textContent,'');await tick();assert.match(f.doc.body.textContent,/previous code may have been replaced/);for(const r of requests){assert.equal(r.method,'POST');assert.equal(r.credentials,'omit');assert.deepEqual(r.headers,{'Content-Type':'application/json'})}});
test('Forget requires a separate confirmation and uncertain result is retryable using the same ID',async t=>{let fail=true;const sent:unknown[]=[];t.mock.method(globalThis,'fetch',async(url:string,init:RequestInit)=>{if(url.endsWith('browsers'))return Response.json({browsers:[entry]});sent.push(JSON.parse(String(init.body)));if(fail)throw Error('offline');return Response.json({result:'already-revoked'})});const f=fixture(t);f.mount.open();await tick();f.button('Forget').click();assert.equal(sent.length,0);f.button('Forget this browser').click();await tick();assert.match(f.doc.body.textContent,/could not be confirmed/);fail=false;f.button('Forget this browser').click();await tick();assert.deepEqual(sent,[{id:entry.id},{id:entry.id}]);assert.match(f.doc.body.textContent,/Browser forgotten/)});
test('closing fences a late code; expiry removes a confirmed code',async t=>{let delayed=true;const gate=deferred();t.mock.method(globalThis,'fetch',async(url:string)=>url.endsWith('browsers')?Response.json({browsers:[]}):delayed?gate.promise:Response.json({code:'123456',expiresInSeconds:300,singleUse:true}));const f=fixture(t);f.mount.open();await tick();f.button('Show pairing code').click();f.mount.close();gate.resolve(Response.json({code:'999999',expiresInSeconds:300,singleUse:true}));await tick();assert.equal(f.output().textContent,'');delayed=false;t.mock.timers.enable({apis:['setTimeout','Date']});f.mount.open();await tick();f.button('Renew pairing code').click();await tick();assert.equal(f.output().textContent,'123456');t.mock.timers.tick(300000);assert.equal(f.output().textContent,'')});
test('refresh preserves the connected confirmation; completion never steals focus from a reader draft',async t=>{const gate=deferred();t.mock.method(globalThis,'fetch',async(url:string)=>url.endsWith('browsers')?Response.json({browsers:[entry]}):gate.promise);const f=fixture(t);f.mount.open();await tick();f.button('Forget').click();const confirm=f.button('Forget this browser');confirm.focus();f.button('Refresh browser list').click();await tick();assert.equal(f.button('Forget this browser'),confirm);assert.equal(f.doc.activeElement,confirm);confirm.click();const draft=f.doc.createElement('textarea');draft.value='reader words';f.doc.body.append(draft);draft.focus();gate.resolve(Response.json({result:'revoked'}));await tick();assert.equal(f.doc.activeElement,draft);assert.equal(draft.value,'reader words')});
test('stale browser list cannot resurrect a confirmed revocation or strand Refresh disabled',async t=>{let reads=0;const list=deferred(),revoke=deferred();t.mock.method(globalThis,'fetch',async(url:string)=>url.endsWith('browsers')?++reads===1?Response.json({browsers:[entry]}):list.promise:revoke.promise);const f=fixture(t);f.mount.open();await tick();f.button('Refresh browser list').click();f.button('Forget').click();f.button('Forget this browser').click();revoke.resolve(Response.json({result:'revoked'}));await tick();list.resolve(Response.json({browsers:[entry]}));await tick();assert.match(f.doc.body.textContent,/Forgotten/);assert.equal(f.button('Refresh browser list').disabled,false);assert.equal(f.doc.body.querySelectorAll('button').some(b=>b.textContent==='Forget'),false)});
test('malformed code and duplicate identities are rejected without replacing trusted visible data',async t=>{t.mock.method(globalThis,'fetch',async(url:string)=>Response.json(url.endsWith('browsers')?{browsers:[entry,entry]}:{code:123456,expiresInSeconds:300,singleUse:true}));const f=fixture(t);f.mount.open();await tick();assert.equal(f.doc.body.querySelectorAll('li').length,0);f.button('Show pairing code').click();await tick();assert.equal(f.output().hidden,true)});
