/** Saved-solver recomputation: run the committed solver again with zero model turns. */
export {
  RECOMPUTE_DIRECTORY,
  discardSolverInput,
  newAttemptToken,
  prepareSolverInput,
  nominalSolverInputPath,
  resolveSolverArtifacts,
  safeRelativeSolverPath,
  type ResolvedSolverArtifacts,
} from './artifacts.ts';
export {
  RPC_MAX_MESSAGE_BYTES,
  SOLVER_EXEC_METHOD,
  SOLVER_OUTPUT_DELTA_NOTIFICATION,
  SOLVER_TERMINATE_METHOD,
  SolverPolicyError,
  commandExecParams,
  createRpcSolverTransport,
  decodeCanonicalBase64,
  execRequestFor,
  outputBytesCapFor,
  readCommandResponse,
  readOutputDelta,
  SOLVER_ALWAYS_STREAMS,
  type CommandExecResult,
  type OutputDeltaRead,
  type SolverCommandObservation,
  type SolverCommandRequest,
  type SolverCommandTransport,
  type SolverExecOptions,
  type SolverStreamObservation,
  type SolverTerminationHandoff,
  type SolverTransportLimits,
} from './transport.ts';
export { SolverResultCache, type SolverCacheEntry, type SolverCacheOptions } from './cache.ts';
export {
  SolverExecutionService,
  type SolverAttemptClaim,
  type SolverAuthority,
  type SolverClaimRelease,
  type SolverClaimReleaseResult,
  type SolverAuthorization,
  type SolverAuthorizationDecision,
  type SolverAuthorizationInput,
  type SolverAuthorizationStage,
  type SolverAuthorizationSubject,
  type SolverContextSource,
  type SolverEvidenceSource,
  type SolverExecutionGate,
  type SolverFinalizationDecision,
  type SolverFinalizationInput,
  type SolverGenerationLease,
  type SolverPreparedCommit,
  type SolverRecomputeContext,
  type SolverServiceOptions,
} from './service.ts';
export {
  createConsentSolverAuthority,
  createStoreSolverContextSource,
  unavailableSolverArtifactBindings,
  unavailableSolverEvidence,
  unavailableSolverExecutionGate,
  type ConsentSolverAuthorityOptions,
  type SolverArtifactBindingSource,
  type SolverJobReader,
  type SolverPermissionReader,
  type SolverReplyReader,
  type StoreSolverContextOptions,
} from './adapters.ts';
export {
  SOLVER_ROUTE_PREFIX,
  createSolverRoutes,
  type SolverRouteRequest,
  type SolverRouteResponse,
  type SolverServiceStatus,
} from './route.ts';
